[package]
name = "common-arrow"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies] # In alphabetical order
# Workspace dependencies

# Github dependencies

arrow = { git="https://github.com/apache/arrow-rs", rev = "0a165748c924b3752cc00ff86e56917427985872" }
arrow-flight = { git="https://github.com/apache/arrow-rs", rev = "0a165748c924b3752cc00ff86e56917427985872" }
parquet = { git="https://github.com/apache/arrow-rs", rev = "0a165748c924b3752cc00ff86e56917427985872", features = ["arrow"] }

# Crates.io dependencies

[dev-dependencies]
