[package]
name = "common-meta-types"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../exception" }
common-io = { path = "../../io" }

openraft = { git = "https://github.com/datafuselabs/openraft", rev = "f633756d60152d171909aea56f80d18905cd4002" }
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1", default-features = false }

anyerror = "0.1.6"
derive_more = "0.99.17"
enumflags2 = { version = "0.7.4", features = ["serde"] }
hex = "0.4.3"
maplit = "1.0.2"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1.10.0"
prost = "=0.10.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sha1 = "0.10.1"
sha2 = "0.10.2"
thiserror = "1.0.30"
tonic = { version = "=0.7.2", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }

[build-dependencies]
common-building = { path = "../../building" }
tonic-build = "=0.7.2"

[dev-dependencies]
anyhow = "1.0.56"
regex = "1.5.5"
