[package]
name = "databend-common-storages-stage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
arrow-schema = { workspace = true }
async-backtrace = { workspace = true }
async-trait = { workspace = true }
bstr = "1.9.1"
csv-core = "0.1.11"
dashmap = { workspace = true }
databend-common-base = { workspace = true }
databend-common-catalog = { workspace = true }
databend-common-compress = { workspace = true }
databend-common-config = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-expression = { workspace = true }
databend-common-formats = { workspace = true }
databend-common-io = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-pipeline-core = { workspace = true }
databend-common-pipeline-sources = { workspace = true }
databend-common-pipeline-transforms = { workspace = true }
databend-common-settings = { workspace = true }
databend-common-sql = { workspace = true }
databend-common-storage = { workspace = true }
databend-common-storages-orc = { workspace = true }
databend-common-storages-parquet = { workspace = true }
databend-storages-common-table-meta = { workspace = true }
enum-as-inner = "0.6.0"
futures = { workspace = true }
log = { workspace = true }
opendal = { workspace = true }
parquet_rs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typetag = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
databend-common-building = { workspace = true }

[lints]
workspace = true
