[package]
name = "common-contexts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../base" }

async-trait = "0.1.53"
opendal = { version = "0.6.3", features = ["retry"] }
time = "0.3.9"
