[package]
name = "tt5"
version = "0.1.0"
edition = "2024"

[dependencies]
bloomfilter = "3.0.1"
arrow = "55.0.0"
parquet = "55.0.0"
xorfilter-rs = { git = "https://github.com/datafuse-extras/xorfilter", tag = "databend-alpha.4" }

