[package]
name = "common-meta-api"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../base" }
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../exception" }
common-meta-types = { path = "../types" }
common-proto-conv = { path = "../../proto-conv" }
common-protos = { path = "../../protos" }
common-tracing = { path = "../../tracing" }

anyerror = "0.1.6"
anyhow = "1.0.56"
async-trait = "0.1.53"
maplit = "1.0.2"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
thiserror = "1.0.30"
tonic = { version = "=0.7.2", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }
