name: Benchmark

on:
  workflow_call:
    inputs:
      sha:
        description: Git sha of benchmark
        required: true
        type: string
      run_id:
        description: The run id of benchmark
        required: true
        type: string
      source:
        description: The source of benchmark, pr/release
        required: true
        type: string
      source_id:
        description: The source id of benchmark, pr number/release tag
        required: true
        type: string
      version:
        description: The version of databend to run
        required: true
        type: string

permissions:
  id-token: write
  pull-requests: write
  contents: read

env:
  BENCHMARK_S3_PREFIX: s3://repo.databend.rs/benchmark/clickbench

jobs:
  local:
    timeout-minutes: 60
    runs-on: [self-hosted, X64, Linux, 16c32g]
    strategy:
      matrix:
        dataset:
          - hits
          # - tpch
      fail-fast: true
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
        if: inputs.source == 'release'
      - uses: actions/checkout@v3
        if: inputs.source == 'pr'
        with:
          ref: "refs/pull/${{ inputs.source_id }}/merge"
      - uses: ./.github/actions/setup_bendsql
      - name: Download artifact
        run: |
          mkdir -p ./target/release
          case ${{ inputs.source }} in
            pr)
              aws s3 sync s3://databend-ci/release/${{ inputs.sha }}/x86_64-unknown-linux-gnu/default/ \
                target/release/ --exclude "*" --include "databend-*" --no-progress
              ;;
            release)
              version=${{ inputs.source_id }}
              target=x86_64-unknown-linux-gnu
              aws s3 cp s3://repo.databend.rs/databend/${version}/databend-${version}-${target}.tar.gz distro/ --no-progress
              tar x -C ./target/release -f ./distro/databend-${version}-${target}.tar.gz --strip-components 1 bin/
              ;;
            *)
              echo "Unknown source: ${{ inputs.source }}"
              exit 1
              ;;
          esac
          chmod +x ./target/release/databend-*
      - name: Setup Databend Binary
        shell: bash
        run: |
          sudo cp ./target/release/databend-* /usr/local/bin/
          databend-query --version
          databend-meta --version
      - uses: ./.github/actions/benchmark_local
        timeout-minutes: 30
        id: benchmark
        with:
          sha: ${{ inputs.sha }}
          run_id: ${{ inputs.run_id }}
          dataset: ${{ matrix.dataset }}
          source: ${{ inputs.source }}
          source_id: ${{ inputs.source_id }}

  cloud:
    timeout-minutes: 90
    runs-on: [self-hosted, X64, Linux, 4c8g]
    strategy:
      matrix:
        include:
          - { dataset: hits, size: Medium }
          - { dataset: hits, size: XLarge }
          - { dataset: tpch, size: Medium }
          - { dataset: tpch, size: XLarge }
      fail-fast: true
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
        if: inputs.source == 'release'
      - uses: actions/checkout@v3
        if: inputs.source == 'pr'
        with:
          ref: "refs/pull/${{ inputs.source_id }}/merge"
      - uses: ./.github/actions/setup_bendsql
      - uses: ./.github/actions/benchmark_cloud
        timeout-minutes: 60
        id: benchmark
        with:
          sha: ${{ inputs.sha }}
          run_id: ${{ inputs.run_id }}
          dataset: ${{ matrix.dataset }}
          source: ${{ inputs.source }}
          source_id: ${{ inputs.source_id }}
          size: ${{ matrix.size }}
          version: ${{ inputs.version }}
          cloud_user: ${{ secrets.BENCHMARK_CLOUD_USER }}
          cloud_password: ${{ secrets.BENCHMARK_CLOUD_PASSWORD }}
          cloud_gateway: ${{ secrets.BENCHMARK_CLOUD_GATEWAY }}

  comment:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: [local, cloud]
    if: inputs.source == 'pr'
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y python3-jinja2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.REPO_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: us-east-2
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-hits
          path: benchmark/clickbench/results/hits
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-tpch
          path: benchmark/clickbench/results/tpch
      - name: Get Report Prefix
        run: |
          echo "REPORT_S3_PREFIX=${{ env.BENCHMARK_S3_PREFIX }}/pr/${{ inputs.source_id }}/${{ inputs.run_id }}" >> $GITHUB_ENV
      - name: Upload PR clickbench result to repo.databend.rs
        working-directory: benchmark/clickbench
        run: |
          aws s3 sync ./results/hits/ ${REPORT_S3_PREFIX}/ --include "*.json"
          aws s3 sync ./results/tpch/ ${REPORT_S3_PREFIX}/ --include "*.json"
      - name: Get latest release clickbench result
        working-directory: benchmark/clickbench
        run: |
          aws s3 sync "${BENCHMARK_S3_PREFIX}/release/hits/latest/" ./results/hits/
          aws s3 sync "${BENCHMARK_S3_PREFIX}/release/tpch/latest/" ./results/tpch/
      - name: Generate clickbench report
        working-directory: benchmark/clickbench
        run: |
          ./update_results.py --dataset hits --pr ${{ inputs.source_id }}
          ./update_results.py --dataset tpch --pr ${{ inputs.source_id }}
      - name: Upload PR clickbench report to repo.databend.rs
        working-directory: benchmark/clickbench
        run: |
          aws s3 cp ./results/hits.html ${REPORT_S3_PREFIX}/hits.html
          aws s3 cp ./results/tpch.html ${REPORT_S3_PREFIX}/tpch.html
      - name: Comment on PR
        uses: everpcpc/comment-on-pr-action@v1
        with:
          number: ${{ inputs.source_id }}
          token: ${{ github.token }}
          body: |
            ![local](https://img.shields.io/static/v1?label=AWS%20EC2&message=c5.4xlarge&color=orange&logo=amazonec2) ![cloud](https://img.shields.io/static/v1?label=Databend%20Cloud&message=Medium&color=blue&logo=icloud) ![cloud](https://img.shields.io/static/v1?label=Databend%20Cloud&message=XLarge&color=blue&logo=icloud)
            ## ClickBench Report
            * **hits**: https://repo.databend.rs/benchmark/clickbench/pr/${{ inputs.source_id }}/${{ inputs.run_id }}/hits.html
            * **tpch**: https://repo.databend.rs/benchmark/clickbench/pr/${{ inputs.source_id }}/${{ inputs.run_id }}/tpch.html

  archive:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: [local, cloud]
    if: inputs.source == 'release'
    strategy:
      matrix:
        dataset:
          - "tpch"
          - "hits"
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y python3-jinja2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.REPO_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: us-east-2
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-${{ matrix.dataset }}
          path: benchmark/clickbench/results/${{ matrix.dataset }}
      - name: Generate report
        working-directory: benchmark/clickbench
        run: |
          aws s3 sync ${{ env.BENCHMARK_S3_PREFIX }}/release/${{ matrix.dataset }}/$(date -u +%Y)/$(date -u +%m)/ ./results/${{ matrix.dataset }}/ --no-progress
          ./update_results.py --dataset ${{ matrix.dataset }} --release ${{ inputs.source_id }}
      - name: Upload nightly results to repo.databend.rs
        working-directory: benchmark/clickbench/
        run: |
          RESULT_PREFIX="${{ env.BENCHMARK_S3_PREFIX }}/release/${{ matrix.dataset }}/$(date -u +%Y)/$(date -u +%m)/$(date -u +%Y-%m-%d)/${{ inputs.source_id }}"
          LATEST_PREFIX="${{ env.BENCHMARK_S3_PREFIX }}/release/${{ matrix.dataset }}/latest/latest"
          for file in ./results/${{ matrix.dataset }}/*.json; do
            aws s3 cp $file "${RESULT_PREFIX}-$(basename $file)"
            aws s3 cp $file "${LATEST_PREFIX}-$(basename $file)"
          done
      - name: Upload PR clickbench report to repo.databend.rs
        working-directory: benchmark/clickbench
        run: |
          aws s3 cp ./results/${{ matrix.dataset }}.html ${{ env.BENCHMARK_S3_PREFIX }}/release/${{ matrix.dataset }}.html
